export const ROLES = [
  "SUPER_ADMIN",
  "ADMIN",
  "FINANCE",
  "HR",
  "TEACHER",
  "STUDENT",
  "PARENT",
  "LIBRARIAN",
  "TRANSPORT",
  "HOSTEL",
] as const;

export const PORTAL_PATHS = {
  STUDENT: "/portal/student",
  TEACHER: "/portal/teacher",
  PARENT: "/portal/parent",
  ADMIN: "/portal/admin",
} as const;

export const DEFAULT_PERMISSIONS = [
  { resource: "students", action: "read" },
  { resource: "students", action: "write" },
  { resource: "teachers", action: "read" },
  { resource: "teachers", action: "write" },
  { resource: "parents", action: "read" },
  { resource: "parents", action: "write" },
  { resource: "classes", action: "read" },
  { resource: "classes", action: "write" },
  { resource: "courses", action: "read" },
  { resource: "courses", action: "write" },
  { resource: "attendance", action: "read" },
  { resource: "attendance", action: "write" },
  { resource: "grades", action: "read" },
  { resource: "grades", action: "write" },
  { resource: "assignments", action: "read" },
  { resource: "assignments", action: "write" },
  { resource: "exams", action: "read" },
  { resource: "exams", action: "write" },
  { resource: "fees", action: "read" },
  { resource: "fees", action: "write" },
  { resource: "payments", action: "read" },
  { resource: "payments", action: "write" },
  { resource: "reports", action: "read" },
  { resource: "settings", action: "read" },
  { resource: "settings", action: "write" },
  { resource: "library", action: "read" },
  { resource: "library", action: "write" },
  { resource: "hostel", action: "read" },
  { resource: "hostel", action: "write" },
  { resource: "transport", action: "read" },
  { resource: "transport", action: "write" },
  { resource: "inventory", action: "read" },
  { resource: "inventory", action: "write" },
  { resource: "hr", action: "read" },
  { resource: "hr", action: "write" },
  { resource: "payroll", action: "read" },
  { resource: "payroll", action: "write" },
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ["*"],
  ADMIN: DEFAULT_PERMISSIONS.map((p) => `${p.resource}:${p.action}`),
  FINANCE: ["fees:read", "fees:write", "payments:read", "payments:write", "reports:read"],
  HR: ["hr:read", "hr:write", "payroll:read", "payroll:write", "teachers:read"],
  TEACHER: [
    "attendance:read", "attendance:write", "grades:read", "grades:write",
    "assignments:read", "assignments:write", "exams:read", "exams:write",
    "students:read", "courses:read",
  ],
  STUDENT: [
    "attendance:read", "grades:read", "assignments:read", "exams:read", "courses:read",
  ],
  PARENT: [
    "students:read", "attendance:read", "grades:read", "fees:read", "payments:read", "payments:write",
  ],
  LIBRARIAN: ["library:read", "library:write"],
  TRANSPORT: ["transport:read", "transport:write"],
  HOSTEL: ["hostel:read", "hostel:write"],
};
